---

- name: Copy requirements.txt
  become: yes
  become_user: "{{wsgi_user}}"
  copy:
    src: "../files/requirements.txt"
    dest: "~{{wsgi_user}}/requirements.txt"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rwx

- name: Install python dependencies
  become: yes
  become_user: "{{wsgi_user}}"
  command: /bin/bash -c "cd; source .venv/bin/activate && pip install -r requirements.txt"

- name: Put a test file in it
  become: yes
  become_user: "{{wsgi_user}}"
  copy:
    src: "../files/wsgi.py"
    dest: "~{{wsgi_user}}/wsgi.py"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rwx,g=r,o=r

- name: Put a uwsgi ini file in it
  become: yes
  become_user: "{{wsgi_user}}"
  copy:
    src: "../files/dummy_susmapi.ini"
    dest: "~{{wsgi_user}}/susmapi.ini"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rw,g=r,o=r

- name: Put the /etc/init/susmapi.service
  become: yes
  copy:
    src: "../files/susmapi.service"
    dest: "/lib/systemd/system/susmapi.service"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rw,g=r,o=r
# systemctl enable susmapi.service
# systemctl start susmapi

- name: Include in nginx
  become: yes
  copy:
    src: "../files/susmapi.nginx"
    dest: "/etc/nginx/sites-available/susmapi"
    owner: www-data
    group: www-data
    mode: u=rw,g=r,o=r

- name: Link to sites-enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/susmapi
    dest: /etc/nginx/sites-enabled/susmapi
    state: link

- name: Remove the default nginx conf.
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart service api, in all cases
  service:
    name: susmapi
    state: restarted

- name: Restart service nginx, in all cases
  service:
    name: nginx
    state: restarted

