---

- name: Create susmapi app directory
  become_user: "{{wsgi_user}}"
  become: yes
  file: path=susmapi state=directory

- name: Put a test file in it
  copy:
    src: "../files/dummy_wsgi.py"
    dest: "~{{wsgi_user}}/susmapi/wsgi.py"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rwx,g=r,o=r

- name: Put a uwsgi ini file in it
  copy:
    src: "../files/dummy_susmapi.ini"
    dest: "~{{wsgi_user}}/susmapi.ini"
    owner: "{{wsgi_user}}"
    group: "{{wsgi_user}}"
    mode: u=rw,g=r,o=r

- name: Put the /etc/init/susmapi.service
  copy:
    src: "../files/susmapi.service"
    dest: "/lib/systemd/system/susmapi.service"
    owner: www-data
    group: www-data
    mode: u=rw,g=r,o=r
# systemctl enable susmapi.service
# systemctl start susmapi

- name: Include in ngix
  copy:
    src: "../files/susmapi.ngix"
    dest: "/etc/nginx/sites-available/susmapi"
    owner: www-data
    group: www-data
    mode: u=rw,g=r,o=r

- name: Link to sites-enabled
  file:
    src: /etc/nginx/sites-available/susmapi
    dest: /etc/nginx/sites-enabled/susmapi
    state: link
  notify: nginx reload
