---
- name: Debian style operating system
  include_tasks: ian.yml
  failed_when: false
  when: ('ian' in group_names) or (ansible_host == '127.0.0.1')

- name: Windows style operating system
  include_tasks: ian.yml
  failed_when: false
  when: 'windows' in group_names
