
all: virtualenv init start configure
clean: stop destroy

virtualenv:
	bin/venv.sh

init:
	bin/init.sh

start:
	bin/start.sh

configure:
	bin/configure.sh

stop:
	bin/stop.sh

destroy:
	bin/destroy.sh