---
- name: Making sure pip and virtualenv are the highest version in {{virtualenv_path}}
  become: yes
  become_user: "{{virtualenv_user}}"
  command: "source {{virtualenv_path}}/bin/activate && pip install --upgrade {{item}}"
  with_items:
    - pip
    - virtualenv
  when: pip_use_latest

- name: Installing packages {{pip_packages|default([])}} in {{virtualenv_path}}
  become: yes
  become_user: "{{virtualenv_user}}"
  command: "source {{virtualenv_path}}/bin/activate && pip install {{item}}"
  with_items: "{{pip_packages|default([])}}"
  when: pip_packages

- name: Installing packages from {{pip_requirements|default("None")}} file in {{virtualenv_path}}
  become: yes
  become_user: "{{virtualenv_user}}"
  command: "source {{virtualenv_path}}/bin/activate && pip install -r {{pip_requirements}}"
  when: pip_requirements is defined

- name: Upgrading packages {{pip_packages|default([])}} in {{virtualenv_path}}
  become: yes
  become_user: "{{virtualenv_user}}"
  command: "source {{virtualenv_path}}/bin/activate && pip install --upgrade {{item}}"
  with_items: "{{pip_packages}}"
  when:
    - pip_upgrade
    - pip_packages

- name: Upgrading packages from {{pip_requirements}} file in {{virtualenv_path}}
  become: yes
  become_user: "{{virtualenv_user}}"
  command: "source {{virtualenv_path}}/bin/activate && pip install --upgrade -r {{pip_requirements}}"
  when:
    - pip_requirements is defined
    - pip_upgrade
