---
- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip 3
  apt:
    name: python3-pip
    state: present

- name: Install virutalenv
  apt:
    name: python3-venv
    state: present
