---
- name: Install Python {{python_major_version}}
  become: true
  apt:
    name: ['python{{python_major_version}}', 'python{{python_major_version}}-pip', 'python{{python_major_version}}-venv']
    state: present
