Vagrant.configure("2") do |config|

  # Virtualbox
  config.vm.box = "debian/stretch64"

  # Adding my key in the VM.
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  ## Using Ansible
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "kafka.yml"
  #end

  config.vm.define "k0" do |k0|

    k0.vm.hostname = 'k0'
    k0.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end

    k0.vm.network :private_network, ip: "10.0.7.10"

    # Set specific SSH port
    #k0.ssh.guest_port = ""
    #k0.vm.network :forwarded_port, guest: 22, host: , id: 'ssh'

  end

  config.vm.define "k1" do |k1|

    k1.vm.hostname = 'k1'
    k1.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end

    k1.vm.network :private_network, ip: "10.0.7.11"

    # Set specific SSH port
    #k1.ssh.guest_port = ""
    #k1.vm.network :forwarded_port, guest: 22, host: , id: 'ssh'

  end

  config.vm.define "k2" do |k2|

    k2.vm.hostname = 'k2'
    k2.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end

    k2.vm.network :private_network, ip: "10.0.7.12"

    # Set specific SSH port
    #k2.ssh.guest_port = ""
    #k2.vm.network :forwarded_port, guest: 22, host: , id: 'ssh'

  end

end