---
- name: Making sure we have the needed packages
  become: yes
  apt:
    pkg:
    - samba
    - smbclient
    - nfs-kernel-server

- name: Making sure we have the backup user
  include_role:
    name: user
  vars:
    name: "{{ backup_user.name }}"
    uid: "{{ backup_user.uid }}"

- name: Make sure we have all people user accounts
  include_role:
    name: user
  vars:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    gid: "{{ item.value.gid | default(item.value.uid) }}"
  loop: "{{ people | dict2items }}"

- name: Making the mount point for the backup drive
  become: yes
  file:
    path: "{{ backup_mountpoint }}"
    state: directory
    mode: 0766

- name: Making sure the backup drive is mounted
  become: yes
  mount:
    src: "{{ backup_device }}"
    path: "{{ backup_mountpoint }}"
    fstype: ext4
    opts: defaults
    passno: 2
    state: mounted

- name: Creating the root NFS export directory
  become: yes
  file:
    path: "{{ nfs_export_path }}"
    state: directory
    mode: 0755

- name: Creating user NFS export dirctories
  become: yes
  file:
    path: "{{ nfs_export_path }}/{{ item }}"
    owner: "{{ backup_user.name }}"
    group: "{{ item }}"
    state: directory
    mode: 0750
  loop: "{{ people | list }}"

- name: Creating extra NFS export directories
  become: yes
  file:
    path: "{{ nfs_export_path }}/{{ item }}"
    owner: "{{ backup_user.name }}"
    group: "{{ backup_user.name }}"
    state: directory
    mode: 0755
  loop: "{{ nfs_extra_exports }}"

- name: Creating mirror NFS export directories
  become: yes
  file:
    path: "{{ nfs_export_path }}/mirror"
    owner: "{{ backup_user.name }}"
    group: "{{ backup_user.name }}"
    state: directory
    mode: 0750

# TODO: Makes sure mountpoint/item/item exists

- name: Mount the user specific directories on the backup drive on on export
  become: yes
  mount:
    src: "{{ backup_mountpoint }}/{{ item }}/{{ item }}"
    path: "{{ nfs_export_path }}/{{ item }}"
    fstype: none
    opts: bind
    passno: 0
    state: mounted
  loop: "{{ people | list }}"

- name: Mount the user specific directories on the backup drive on on export
  become: yes
  mount:
    src: "{{ backup_mountpoint }}/{{ item }}"
    path: "{{ nfs_export_path }}/{{ item }}"
    fstype: none
    opts: bind
    passno: 0
    state: mounted
  loop: "{{ nfs_extra_exports }}"

- name: Mount the user specific directories on the backup drive on on export
  become: yes
  mount:
    src: "{{ backup_mountpoint }}"
    path: "{{ nfs_export_path }}/mirror"
    fstype: none
    opts: bind
    passno: 0
    state: mounted

- name: Configuring the user NFS exports
  become: yes
  lineinfile:
    path: /etc/exports
    regexp: "^{{ nfs_export_path }}/{{ item }}"
    line: "{{ nfs_export_path }}/{{ item }} {{ nfs_allow_from }}({{ nfs_options }})"
  loop: "{{ people | list }}"
  notify: restart nfs

- name: Configuring the extra NFS exports
  become: yes
  lineinfile:
    path: /etc/exports
    regexp: "^{{ nfs_export_path }}/{{ item }}"
    line: "{{ nfs_export_path }}/{{ item }} {{ nfs_allow_from }}({{ nfs_options }})"
  loop: "{{ nfs_extra_exports }}"
  notify: restart nfs

- name: Configure the general mirror exports
  become: yes
  lineinfile:
    path: /etc/exports
    regexp: "^{{ nfs_export_path }}/mirror"
    line: "{{ nfs_export_path }}/mirror {{ nfs_allow_from }}({{ nfs_options }})"
  notify: restart nfs
