---
- hosts: ian
  tasks:
  - name: Update and upgrade apt packages
    when: ansible_os_family == "Debian"
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Clean apt cach
    when: ansible_os_family == "Debian"
    command: apt-get clean
    become: yes
