Vagrant.configure("2") do |config|

  # Virtualbox
  config.vm.box = "centos/7"
  config.vm.hostname = 'ws0-vb'
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  ## Using my ssh key.
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.guest_port = "2222"

  # Adding my key in the VM.
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # Using Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "was" => ["ws0", "ws0-vb"]
    }
  end

  # Port forwarding
  config.vm.network "forwarded_port", guest: 9060, host: 9060

end
