---
sync_directories_to_backup:
  - "Documents"
  - "Pictures"
  - "public_html"
  - "Video's"
sync_user: "{{ config.backup.backup_user.name }}"
sync_group: "{{ config.backup.backup_user.group | default(config.backup.backup_user.name) }}" 
sync_uid: "{{ config.backup.backup_user.uid }}"
sync_gid: "{{ config.backup.backup_user.gid | default(config.backup.backup_user.uid) }}"
nfs_export_path: "{{ config.backup.nfs_export_path }}"
