---
- name: Main playbook for everything (only testsusmapi for now).
  hosts: all
  vars:
    wsgi_user: susmapi
  tasks:
    - name: Update and upgrade all packages.
      import_role:
        name: latest
      when: latest_packages is defined

    - name: Install a test wsgi application
      import_role:
        name: testsusmapi
      when: ansible_hostname in groups['susm-api']
