---
- name: This playbook will install the SUSM API server.
  hosts: susm-api
  vars:
    wsgi_user: susmapi
  tasks:
    - name: Update and upgrade all packages.
      import_role:
        name: latest
      when: latest_packages is defined

    - name: Install a test wsgi application
      import_role:
        name: testsusmapi
