---
- name: Update and upgrade apt packages
  become: true
  when: ansible_os_family == "Debian"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Clean apt cach
  when: ansible_os_family == "Debian"
  become: true
  command: apt-get clean
